### ISSUE TITLE
Automatically process new tickets

### ISSUE THREAD

**Issue by rafibarash** [csci4950tgt/honeyclient#14]
This way we won't have to individually start the honeyclient after creating a new ticket, it will do it automatically if the honeyclient event loop is running

**Comment by tantric-slug** [comment]
Im gonna implement slightly similar but more resource intensive functionality of this through exec commands in the API. 

This is something to implement in the future as it could improve response time to the user by already having all of the necessary framework set up to process the tickets instead of having to spawn a distinct process.
